CREATE TABLE EXISTSIN
(
[ITEMCODE] [INT] NOT NULL,
[STORECODE] [INT] NOT NULL,
[QUANTITY] [INT] NOT NULL,
[AISLE_NO] [VARCHAR] (2) NOT NULL,
PRIMARY KEY(ITEMCODE,STORECODE),
FOREIGN KEY(ITEMCODE) REFERENCES ITEM(ITEMCODE),
FOREIGN KEY(STORECODE) REFERENCES STORE(STORECODE)
)