CREATE TABLE PERSON
(
[PERSONCODE] [INT] NOT NULL,
[ADDRESSCODE] [INT] NOT NULL,
[FIRSTNAME] [VARCHAR] (50) NOT NULL,
[LASTNAME] [VARCHAR] (50) NOT NULL,
[EMAIL] [NVARCHAR] (50) NOT NULL,
[DOB] [DATE] NOT NULL,
PRIMARY KEY(PERSONCODE),
FOREIGN KEY (ADDRESSCODE) REFERENCES ADDRESS(ADDRESSCODE),
)