CREATE TABLE STORE
(
[STORECODE] [INT] NOT NULL,
[DEPARTMENTS] [VARCHAR] (70) NOT NULL,
[ADDRESSCODE] [INT] NOT NULL,
PRIMARY KEY(STORECODE),
FOREIGN KEY(ADDRESSCODE) REFERENCES ADDRESS(ADDRESSCODE)
)