CREATE TABLE TRANSACTIONS
(
[TRANSACTIONCODE] [INT] NOT NULL,
[PERSONCODE] [INT] NOT NULL,
[STORECODE] [INT] NOT NULL,
[TRANSACTION_DATE] [DATE] NOT NULL,
[PAYMENT_METHOD] [VARCHAR] (50) NOT NULL,
PRIMARY KEY(TRANSACTIONCODE),
FOREIGN KEY(PERSONCODE) REFERENCES PERSON(PERSONCODE),
FOREIGN KEY(STORECODE) REFERENCES STORE(STORECODE)
)
